application:
  appName: ecommerce

  mail:
    endereco-remetente: basistreinamento@gmail.com
    nome-remetente: ecommerce

spring:
  application:
    name: ecommerce-service

    cloud:
      stream:
        bindings:
          mailer:
            destination: mailer

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: ecommerce
    password: ecommerce

    hikari:
      poolName: Hikari
      auto-commit: false

  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: false

  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false

  liquibase:
    change-log: classpath:/config/liquibase/master.xml
  #        drop-first: true

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: basistreinamento@gmail.com
    password: basis123123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          quitwait: false

server:
  port: 8080

